const Sdata = [
  {
    id: 1,
    sname: "Kochi, Kerala, India",
    imgsrc: "Incognito World",
    title: "Frontend Web Developer",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=29032210&f_WRA=true&geoId=102713980",
  },
  {
    id: 2,
    sname: "Bangluru, India",
    imgsrc: "Urban Plants",
    title: "Web Developer",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2615142859&f_WRA=true&geoId=102713980",
    comname: "Urban Plant",
  },
  {
    id: 3,
    sname: "Chennai, India",
    imgsrc: "AiSensys",
    title: "Software Engineer",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2589534823&f_WRA=true&geoId=102713980",
  },
  {
    id: 4,
    sname: "India",
    imgsrc: "Latitude Technolabs Pvt. Ltd.",
    title: "JavaScript Developer",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2601313540&f_WRA=true&geoId=102713980",
  },
  {
    id: 5,
    sname: "India",
    imgsrc: "web sense",
    title: "Web Developer",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2577841320&f_WRA=true&geoId=102713980",
  },
  {
    id: 6,
    sname: "India",
    imgsrc: "Visionkrid Studio Pvt Ltd",
    title: "React js",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2608876794&f_WRA=true&geoId=102713980",
  },
  {
    id: 7,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 8,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 9,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 10,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 11,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 12,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 13,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
  {
    id: 14,
    sname: "India",
    imgsrc: "LetsGrowMore",
    title: "Web Development Intern",
    link: "https://www.linkedin.com/jobs/search/?currentJobId=2619681222&f_WRA=true&geoId=102713980",
  },
];

export default Sdata;
